# Generated by Django 4.1.1 on 2023-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='省市')),
                ('value', models.CharField(max_length=255, verbose_name='数值')),
                ('unit', models.CharField(max_length=255, verbose_name='单位')),
                ('zb', models.CharField(max_length=255, verbose_name='指标')),
                ('updateTime', models.CharField(max_length=255, verbose_name='更新年份')),
            ],
            options={
                'verbose_name': '农业数据',
                'verbose_name_plural': '农业数据',
                'db_table': 'agriculture',
            },
        ),
        migrations.CreateModel(
            name='Meteorology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='城市')),
                ('month', models.CharField(max_length=255, verbose_name='月份')),
                ('avg_max_temperature', models.CharField(max_length=255, verbose_name='平均最高气温')),
                ('avg_min_temperature', models.CharField(max_length=255, verbose_name='平均最低气温')),
                ('avg_precipitation', models.CharField(max_length=255, verbose_name='平均降水量')),
                ('histroy_max_temperature', models.CharField(max_length=255, verbose_name='历史最高气温')),
                ('histroy_min_temperature', models.CharField(max_length=255, verbose_name='历史最低气温')),
            ],
            options={
                'verbose_name': '气候数据',
                'verbose_name_plural': '气候数据',
                'db_table': 'meteorology',
            },
        ),
    ]
